spring:
  datasource:
    url: jdbc:postgresql://localhost/employee-dev
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true